create table db1.table_G (
column_QM_UK string
,column_TS_GC string
,column_ZE_SU int64
,column_OD_BK int64
,column_ID_AO date
,column_IH_OE int64
,column_LG_HI date
,column_OK_CH date
,column_LN_OO int64
,column_MB_YA int64
,column_TI_IO int64
,column_CB_WT int64
,column_DX_QZ string
,column_JB_TN string
,column_RM_XW string
,column_OO_UJ string
,column_PJ_FI string
,column_JK_DE string
,column_AN_RJ string
,column_QG_SR string
,column_BA_ES int64
,column_CG_CE int64
,column_AD_MF int64
,column_DH_FT string
,column_UL_IV int64
,column_NK_HL string
,column_TD_RU string
,column_QC_HX string
,column_KC_IF int64
,column_ZY_HK int64
,column_YH_MO int64
,column_UW_TD int64
,column_EW_IE int64
,column_KF_DV date
,column_QG_YO int64
,column_SV_VC int64
,column_GA_JT int64
,column_CT_GJ int64
,column_GS_CI int64
,column_NI_OE string
,column_EM_OZ int64
,column_BW_UI int64
,column_ND_VD int64
,column_VD_GB int64
,column_PA_AW string
,column_RG_UA string
,column_LA_OO string
,column_RF_UM string
,column_TN_ZU string
,column_CC_OJ string
,column_YE_QF string
,column_XX_AE string
,column_VN_IQ string
,column_SS_SD string
,column_CA_SL int64
,column_JA_WR string
,column_TW_OA int64
,column_NY_XT int64
,column_CS_VS string
,column_EH_IC date
,column_OA_BM int64
,column_DG_QG int64
,column_OY_HH int64
,column_YL_HE string
,column_CZ_LU string
,column_XB_PM int64
,column_NF_EO int64
,column_NU_TG int64
,column_UQ_ZJ int64
,column_CG_OW int64
,column_TB_CX string
,column_MW_IN int64
,column_IM_NM int64
,column_IP_IK int64
,column_NO_HG int64
,column_QQ_UX date
,column_YI_NA int64
,column_SM_KE date
,column_VO_NF string
,column_AU_JK int64
,column_GE_ME int64
,column_OG_OA int64
,column_CM_NQ int64
,column_SG_GU string
,column_EH_DT string
,column_BM_DY int64
,column_GE_SC int64
,column_MS_DG int64
,column_HP_DU int64
,column_CG_VG int64
,column_OJ_SB int64
)
;
