create table db1.table_D (
column_TC_RR string
,column_LW_IE string
,column_WN_TU int64
,column_TD_RV string
,column_TP_QV string
,column_FD_GV string
,column_HG_XD string
,column_WC_BI string
,column_WR_XA string
,column_WP_IQ string
,column_TI_WD string
,column_WI_IY string
,column_WX_IP string
,column_TO_DB string
,column_SG_RF string
,column_PB_VL date
,column_ZT_LT string
,column_WJ_EK date
,column_GE_JY string
,column_DV_SZ string
,column_BV_MR string
,column_RR_YG date
,column_RP_HQ string
,column_CF_QJ string
,column_FN_AR string
,column_QN_QF string
,column_QG_QV string
,column_OC_MN string
,column_US_QI string
,column_DY_AH string
,column_ON_WY string
,column_TV_KP string
,column_AP_ZD string
,column_EX_MV string
,column_UU_FE int64
,column_PH_QO string
,column_RL_XW string
,column_KN_AI int64
,column_KW_QZ int64
,column_LD_PN int64
,column_TL_OR string
,column_TK_YR int64
,column_SQ_PP int64
,column_RP_SS int64
,column_OS_XZ string
,column_EU_GQ date
,column_UJ_HN date
,column_SG_DQ date
,column_OB_RV int64
,column_KG_VW int64
,column_VP_HB int64
,column_CV_KR int64
,column_YK_PT int64
,column_MW_YF int64
,column_FO_IE string
,column_BG_TM int64
,column_MP_JL int64
,column_HQ_JT int64
,column_MG_HE int64
,column_TU_RW int64
,column_AK_DT date
,column_YL_LW date
,column_MH_CK string
,column_GP_II date
,column_FN_IK string
,column_SN_OE string
,column_QI_LH string
,column_GR_VN string
,column_BF_TN int64
,column_WJ_FO int64
,column_MU_NY string
,column_KM_EM string
,column_NQ_VI int64
,column_NR_TC string
,column_LO_DD int64
,column_MF_TO string
,column_OQ_OJ string
,column_ZB_KH string
,column_FB_LV int64
,column_YA_RL int64
,column_SL_BD string
,column_TM_AF int64
,column_JW_DR int64
,column_HY_SF int64
,column_KV_NB int64
,column_SF_HT int64
,column_SW_BH string
,column_SZ_RA string
,column_NQ_GJ int64
,column_KY_GN int64
,column_EE_XN int64
,column_CG_CU int64
,column_JV_VB string
,column_HV_BP int64
,column_RD_AC int64
,column_MR_GL int64
,column_ON_NP string
)
;
