create table db1.table_K (
column_OQ_PO date
,column_QR_RS string
,column_WZ_MK string
,column_SM_QM string
,column_TQ_BL date
,column_HH_XW int64
,column_NM_PZ int64
,column_UP_TL string
,column_XF_OU int64
,column_UP_HR string
,column_XM_QB int64
,column_PT_TH string
,column_GB_TH string
,column_WX_SE string
,column_KW_WH date
,column_TJ_QA int64
,column_VK_XR string
,column_XG_VZ int64
,column_XT_MW string
,column_CT_ZV int64
,column_ZR_TI string
,column_AE_ND int64
,column_LM_WK int64
,column_MN_AD int64
,column_EV_EO int64
,column_FN_RN string
,column_XG_DI string
,column_QL_WM int64
,column_GH_TV int64
,column_NE_GQ string
,column_SE_WU int64
,column_UY_CL int64
,column_EF_QK int64
,column_RP_QR date
,column_OA_CU int64
,column_CQ_IZ int64
,column_YO_FN int64
,column_OI_SH int64
,column_MQ_QM string
,column_TV_ND string
,column_SP_DF string
,column_NL_KO string
,column_QW_KH string
,column_ET_YT string
,column_NF_JY string
,column_TD_UA string
,column_YI_CK string
,column_EG_NQ string
,column_CR_CE int64
,column_BC_UQ string
,column_AA_OO string
,column_OT_EX string
,column_WF_VQ date
,column_OZ_NT string
,column_LP_TN int64
,column_NQ_GF int64
,column_WE_IU int64
,column_BY_MA int64
,column_QQ_FR string
,column_LS_MZ int64
)
;
