create table db1.table_V (
column_RL_CC string
,column_WW_XU int64
,column_VF_SU int64
,column_PB_TO string
,column_TU_NL int64
,column_BK_DZ string
,column_ZN_EW string
,column_ZJ_GK string
,column_KK_YW int64
,column_DT_FV string
,column_MD_PG date
,column_RY_FR string
,column_VA_LP string
,column_VN_AW string
,column_VK_LK string
,column_PS_TP date
,column_SJ_IB string
,column_VP_IU string
,column_OV_NH string
,column_KE_WC string
,column_QS_DU string
,column_WN_TA date
,column_OO_ID int64
,column_VM_JL string
,column_CF_CT string
,column_JK_IM int64
,column_NN_UK string
,column_TS_PN string
,column_TB_JQ string
,column_TS_NO string
,column_MY_IR int64
,column_AI_TL int64
,column_TS_ZO string
,column_XJ_ZI string
,column_YL_KJ string
,column_NR_TJ string
,column_ZT_LV string
,column_TA_AN string
,column_TL_OH string
,column_QS_GF int64
,column_XJ_QY int64
,column_OV_ZZ date
,column_PV_OL string
,column_WM_DI string
,column_ST_DQ string
,column_RA_PC int64
,column_DP_PR int64
,column_ZH_UY string
,column_CT_YU string
,column_VL_IJ string
,column_XJ_LU int64
,column_XG_LE int64
,column_ML_FS int64
,column_MC_BH date
,column_YB_BT int64
,column_QH_FE int64
,column_WN_ZV int64
,column_KX_HU string
,column_SE_MU string
,column_HW_HI string
,column_TZ_JL string
,column_LP_PA string
,column_NV_RI string
,column_NZ_EO string
,column_HU_KW date
,column_NH_ET int64
,column_MR_YS string
,column_WO_GC string
,column_JG_QB string
,column_JA_KU string
,column_TQ_NZ int64
,column_XI_CR string
,column_GI_ER string
,column_UC_UU string
,column_KU_MQ int64
,column_KF_CZ date
,column_GI_LD string
,column_RI_PV string
,column_VH_UL string
,column_RT_WK string
,column_XN_ZF int64
,column_LL_PC string
,column_WM_QM string
,column_MS_HG int64
,column_OS_CT int64
,column_AE_RD string
,column_QO_VW string
,column_ME_TD string
,column_XO_CB string
,column_TK_NT string
,column_VN_QN string
,column_VB_DQ string
,column_VL_VD string
,column_VX_SK string
,column_AD_QD string
,column_JY_EH date
,column_II_FM string
,column_HW_WT string
,column_GE_IM string
,column_VS_PA string
,column_SR_OO int64
,column_RS_LO int64
,column_UJ_HD int64
,column_TG_DC int64
,column_TD_TG string
,column_VW_NC date
,column_IB_CP date
,column_HI_ML date
,column_UP_ZG date
,column_CZ_HK int64
,column_DQ_AH int64
,column_KI_JN string
,column_NG_DB string
,column_HE_CX string
,column_TU_NV string
,column_JP_FS string
,column_FX_LD date
,column_RW_RO int64
,column_DE_SQ string
,column_TJ_CA int64
,column_OR_LB string
,column_VW_TE string
,column_FA_UY string
,column_FL_IR int64
,column_QF_RS string
,column_KJ_HJ int64
,column_JH_BN int64
,column_JK_MM int64
,column_CP_QF int64
,column_UL_CV int64
,column_NV_EZ int64
,column_RF_FU int64
,column_LI_EN string
,column_UP_NV int64
,column_XE_TE int64
,column_AM_VO int64
,column_AZ_JS int64
,column_GH_NL date
,column_KG_GH string
,column_HO_CK int64
,column_IS_MA int64
,column_MA_ZN string
,column_SS_AT string
)
;
