create table db1.table_J (
column_LU_VA string
,column_TN_PD int64
,column_KF_QX string
,column_KT_XJ string
,column_QM_QH string
,column_QC_LF string
,column_MC_WF int64
,column_IL_AV string
,column_NE_TW string
,column_FF_FD date
,column_MJ_EY string
,column_JC_OO int64
,column_QH_CY string
,column_DP_NL string
,column_KX_AH string
,column_UK_DC int64
,column_RY_AQ string
,column_MG_DD int64
,column_ZN_BQ date
,column_TA_FT string
,column_PN_KX string
,column_KL_BK string
,column_JA_BG string
,column_OR_ME string
,column_CJ_UP int64
,column_HS_YS string
,column_FN_VN string
,column_KD_RY date
,column_JZ_QF int64
,column_DH_PU string
,column_YO_OV string
,column_KT_CF date
,column_EL_NH int64
,column_OF_CE date
,column_FW_FW string
,column_HF_ZB string
,column_VS_TX int64
,column_NW_UH string
,column_VU_FX string
,column_HP_ME string
,column_CC_IE string
,column_PT_JD string
)
;
