create table db1.table_Y (
column_AB_ZR int64
,column_DA_LM int64
,column_NW_TN int64
,column_XN_QZ int64
,column_LC_MR string
,column_TK_DJ string
,column_XX_VW string
,column_TN_CY string
,column_ZQ_VK string
,column_NP_UP string
,column_JT_OW string
,column_CI_UP string
,column_OE_AN date
,column_KU_DX date
,column_MJ_XV date
,column_PS_XN string
,column_SE_LG string
,column_OZ_NW int64
,column_TY_QY int64
,column_XL_BZ int64
,column_WK_IN date
,column_JF_IH string
,column_DZ_LF string
,column_JA_LJ int64
,column_VG_NG string
,column_KB_NU string
,column_OY_SX string
,column_RL_NH int64
,column_XJ_KI int64
,column_XQ_GM string
,column_VR_EI string
,column_GY_EM string
,column_HF_EM string
,column_MG_CB date
,column_LW_SI string
,column_ZF_NH string
,column_VE_OV string
,column_RS_MG string
,column_VM_RT string
,column_VP_QB string
,column_TU_CL string
,column_ZV_CJ string
,column_NG_ON string
,column_ZP_XC string
,column_CG_YT string
,column_WL_WK string
,column_KI_MO string
,column_VD_OV string
,column_ND_AR int64
,column_UC_MH int64
,column_WG_NC int64
,column_VN_AL string
,column_RI_IR string
,column_QM_QW string
,column_SN_KF string
,column_KF_XT int64
,column_QJ_ME int64
,column_AK_OS string
,column_QR_GD string
,column_MM_LH string
,column_XC_GE string
,column_TM_ZS string
,column_VC_UF string
,column_VG_BU string
,column_VN_NY string
,column_VN_NF string
,column_AR_OM string
,column_JK_MR date
,column_IA_PN string
,column_HK_QB string
,column_GQ_YU string
,column_VC_PW string
,column_SB_GB int64
,column_RB_WT int64
,column_UD_LG int64
,column_TF_XL int64
,column_TP_RS string
,column_VB_QE date
,column_EY_RN int64
,column_UR_BX date
,column_TW_RG date
,column_IT_IE date
,column_HU_TD date
,column_IU_NS int64
,column_HX_JM int64
,column_HN_MG string
,column_CU_VF int64
,column_WZ_QW string
,column_TO_IE string
,column_MJ_JU string
,column_TF_JV string
,column_HA_IT date
,column_FV_TX int64
,column_CJ_QZ int64
,column_UV_QD string
,column_JV_FD string
,column_GE_KQ string
,column_NL_CM string
,column_FH_RH date
,column_NN_ZW string
,column_TG_NH int64
,column_PU_DH date
,column_QX_NS string
,column_FR_LP string
,column_TP_VB string
,column_TM_KA string
,column_ND_NF int64
,column_LM_LH string
,column_TU_YU string
,column_ZA_EE date
,column_YK_UO date
,column_SH_DI string
,column_TW_UF string
,column_US_MB string
,column_XL_GP string
,column_AG_PJ string
,column_FI_BD date
,column_AJ_IG string
,column_EM_HV date
,column_YL_WF string
,column_QI_LL string
,column_EE_QO int64
,column_UL_MO date
,column_TY_TX date
,column_HC_JU date
,column_IC_KF int64
,column_HM_JP int64
,column_HY_PX string
,column_CX_AP int64
,column_DG_MZ timestamp
,column_DI_MG int64
,column_CN_JJ string
,column_EB_UZ timestamp
,column_ID_TJ date
,column_KJ_OF string
,column_FF_JB date
,column_TE_OD int64
,column_CQ_OT int64
,column_RW_OC string
,column_XA_KM string
,column_TC_LR string
,column_UZ_EU timestamp
,column_LN_DB string
,column_NU_AJ string
,column_RL_OX string
,column_GN_NK string
,column_YZ_OD string
,column_BM_JJ string
,column_PE_NG string
,column_OT_YV string
,column_VV_UB string
,column_NG_XU string
,column_US_CV int64
,column_CC_QH string
,column_KA_BE string
,column_NV_OJ string
,column_XF_IB date
,column_WL_RR int64
,column_RI_KK date
,column_DL_FJ int64
,column_YK_QG date
,column_JF_WD int64
,column_XN_NJ int64
,column_JM_KW string
,column_IB_VJ timestamp
,column_NZ_QN string
,column_XA_PN string
,column_XA_NP string
,column_KA_AF string
,column_OL_JT string
)
;
