create table db1.table_H (
column_ON_XA int64
,column_SD_QC int64
,column_WC_IG string
,column_KM_XC int64
,column_LJ_TK date
,column_WN_XG date
,column_SN_FV date
,column_FP_CM string
,column_CP_CP string
,column_CQ_HV string
,column_BL_EM string
,column_BP_WB string
,column_OK_WN string
,column_RV_KX string
,column_BT_LS string
,column_BS_EG string
,column_BX_XY string
,column_BQ_IO string
,column_HJ_HY string
,column_XB_FK string
,column_JJ_QO string
,column_WF_OB string
,column_XK_HY int64
,column_BZ_IH int64
,column_ZR_UE int64
,column_XR_TM int64
,column_MT_OA int64
,column_OK_OI int64
,column_QZ_CU int64
,column_HC_PE string
,column_NF_FF string
,column_PX_OJ int64
,column_MR_JH int64
,column_BR_YL string
,column_RR_KA string
,column_IT_JX string
,column_WT_RM string
,column_LF_WY string
,column_KT_HJ int64
,column_RV_VX int64
,column_KU_YU int64
,column_MJ_EG int64
,column_TU_KX int64
,column_OX_HO int64
,column_ZS_DP string
,column_CV_TA string
,column_MQ_AS string
,column_OJ_SK string
,column_UJ_FR string
,column_IM_JQ string
,column_BA_RF int64
,column_EP_BS int64
,column_UW_EC date
,column_TL_SS date
,column_IR_KC date
,column_HK_VB date
,column_II_QC int64
,column_HP_AP string
,column_CJ_JT int64
,column_RM_CX string
,column_DW_VG timestamp
,column_DW_FS int64
,column_CN_IQ string
,column_EA_CN timestamp
,column_FN_QN string
,column_BY_IV string
,column_RY_YC int64
,column_OV_AJ string
,column_YP_NV string
,column_FN_TL string
,column_CI_GM int64
,column_YG_YJ string
,column_WQ_LI string
,column_VY_NM string
,column_ME_MG int64
,column_OL_ZC int64
,column_RO_SO string
,column_DN_HX string
,column_HA_DQ int64
,column_DP_II int64
,column_ZN_YZ string
,column_RO_BT string
,column_UB_FD int64
,column_DN_TA int64
,column_XN_GQ int64
,column_TF_IU string
,column_ZE_IG int64
,column_RK_ES date
,column_DA_VO int64
,column_HE_VI date
)
;
