create table db1.table_Q (
column_QY_IP string
,column_GO_LF string
,column_LT_DN string
,column_CH_UU string
,column_BT_KL string
,column_YO_CC string
,column_MS_KU string
,column_OL_AB string
,column_MD_CV string
,column_OC_IN string
,column_QU_EE string
,column_JB_FR string
,column_VW_TM string
,column_QC_ET string
,column_EO_HC string
,column_EO_CO string
,column_XS_CG date
,column_NK_NG date
,column_LL_RW int64
,column_LA_KC string
,column_SC_QG string
,column_BZ_PI int64
,column_EG_DL string
,column_DJ_JK string
,column_WF_RG string
,column_NW_ZS string
,column_CV_FP string
,column_QK_BS string
,column_OI_MD string
,column_IM_SV int64
,column_XS_RK string
,column_PF_PQ string
,column_YD_AW string
,column_MJ_LQ string
,column_LB_UH string
,column_MG_AI string
,column_XC_YD string
,column_ZH_NL string
,column_LF_IK string
,column_IT_WT string
,column_DG_LP int64
,column_NI_ZT string
,column_EJ_TJ string
,column_WS_GF string
,column_NZ_FU string
,column_JW_UN int64
,column_NL_UW string
,column_VN_RK date
,column_NC_ZE string
,column_KW_IZ string
,column_IE_RD string
,column_SX_DJ string
,column_IB_VU string
,column_GC_UL string
,column_XB_SV date
)
;
