create table db1.table_Z (
column_PP_ZU string
,column_JM_ZL int64
,column_GF_AA int64
,column_XK_JC string
,column_QB_VB string
,column_SI_KH string
,column_RA_EX int64
,column_DK_IP int64
,column_ZQ_NM string
,column_KB_FT string
,column_UJ_UZ string
,column_NQ_VM int64
,column_XL_WB string
,column_NV_NE string
,column_LD_UW string
,column_NG_AC string
,column_YK_AX string
,column_CM_PA string
,column_CN_PQ string
,column_MQ_AU string
,column_MJ_FP string
,column_BH_CO string
,column_GW_HW string
,column_PI_VC int64
,column_IY_LJ string
,column_NT_PT string
,column_LP_DR string
,column_NV_YN int64
,column_SA_SL string
,column_CE_GQ string
,column_MG_FS string
,column_CG_GW string
,column_CR_RK string
,column_CG_YB string
,column_CF_VK string
,column_CS_LO string
,column_YA_LI int64
,column_OQ_NP int64
,column_VW_NG string
,column_AJ_TQ int64
,column_MP_TO string
,column_NE_BB string
,column_EN_BJ string
,column_RP_RW int64
,column_IO_GW int64
,column_KC_UU int64
,column_MJ_BU string
,column_LO_DU string
,column_MS_KE string
,column_UG_DW string
,column_CR_CY string
,column_XR_XJ string
,column_GO_DO string
,column_QB_CI string
,column_HT_FI string
)
;
