create table db2.table_F (
column_MD_WB int64
,column_CN_DB string
,column_UP_AG string
,column_NL_AH string
,column_TT_HK string
,column_AI_BZ string
,column_MF_DH string
,column_FT_ZO string
,column_MB_UG int64
,column_LQ_FQ string
,column_NJ_DZ string
,column_ND_WH string
,column_NF_UB string
,column_ND_ML string
,column_NX_LQ string
,column_AW_ZR string
,column_EP_GQ string
,column_SK_SZ string
,column_OV_QV string
,column_QK_AZ string
,column_IM_KO string
,column_LG_JP string
,column_LY_JZ string
,column_JC_LX string
,column_JE_FO string
,column_PF_WL string
,column_JP_QA string
,column_HI_TQ string
,column_PT_KJ string
,column_CQ_GW int64
,column_HX_VQ int64
,column_FK_EX date
,column_DN_OC date
,column_ES_CU string
,column_EC_DU string
,column_PW_BZ int64
,column_QB_SZ string
,column_KW_CS string
,column_SD_DS string
,column_QE_ST string
,column_OV_TO string
,column_ER_CA int64
,column_MU_CG int64
,column_GE_LJ string
,column_FH_FH string
,column_MF_MU string
,column_DU_IV string
,column_MM_CE string
,column_SC_TV string
,column_JW_QL string
,column_NV_YJ string
,column_QH_ND string
,column_GH_SL string
,column_JR_UL string
,column_YT_UP string
)
;
