create table db2.table_N (
column_UG_HL date
,column_AL_KC int64
,column_CI_SF int64
,column_DS_KU string
,column_BX_GT int64
,column_GP_YP int64
,column_YX_KY int64
,column_TX_RI string
,column_ZX_UW int64
,column_NX_PL string
,column_RE_YO int64
,column_TV_OG int64
,column_OM_CX string
,column_QM_YN string
,column_CV_QD string
,column_IM_NV int64
,column_MH_MV string
,column_NS_XI string
,column_ZS_EO string
,column_QF_QG string
,column_DP_YZ string
,column_WF_NU string
,column_AV_BQ int64
,column_JN_ZB string
,column_QV_OC string
,column_OX_MD string
,column_OG_CG int64
,column_TC_UV string
,column_YE_OE string
,column_ML_LO int64
,column_NH_QP string
,column_QW_SJ int64
,column_SA_HQ int64
,column_DT_SF int64
,column_CH_EI string
,column_AM_EB string
,column_QW_DB string
,column_LA_LV string
,column_RM_AT string
,column_OV_PS string
,column_SL_NA string
,column_RT_OU string
,column_TO_RL string
,column_EM_OF int64
,column_EO_SB int64
,column_MM_IJ int64
,column_OT_BV int64
,column_NI_UF int64
,column_VV_BN string
,column_CL_II string
,column_ZS_UI string
,column_LL_IR string
,column_KK_GR string
,column_PC_YM string
,column_BH_WQ string
,column_IL_OC string
,column_TM_YC string
,column_HU_BC string
,column_DJ_NY string
,column_RZ_VU int64
,column_FU_WR string
,column_GS_HT string
,column_FK_GR string
,column_EQ_SI string
,column_GR_LB string
,column_NV_MU string
,column_ME_BL string
,column_ID_IT string
,column_RN_BB string
,column_YJ_PF string
,column_GZ_VJ int64
,column_DG_MI int64
,column_OX_FG string
,column_ZT_UZ string
,column_CJ_AR string
,column_YM_FI string
,column_CE_IE string
,column_HT_UV string
,column_EM_UQ string
,column_IZ_EB string
,column_FH_XX string
,column_QM_WT string
,column_PT_LF string
,column_VG_TX string
,column_RZ_KB string
,column_LG_VO string
,column_RV_RZ string
,column_TE_RA string
,column_MH_GL string
,column_SX_OJ string
,column_HD_CP string
,column_HU_SK string
,column_IM_OO int64
,column_MO_NK string
,column_VF_BH string
,column_WP_SQ string
,column_RN_ZT string
,column_EH_AN string
,column_KF_HH string
,column_GU_BH string
,column_XW_ZQ int64
,column_KM_NR string
,column_JP_SQ string
,column_BR_EK string
,column_BF_RQ string
,column_SX_KA int64
,column_NV_FF string
,column_FO_GK string
,column_CB_LU int64
,column_HQ_DO int64
,column_FI_SG date
,column_DT_PJ date
,column_QE_JK string
,column_KR_TF string
,column_XV_ZE string
,column_ER_JF date
,column_DA_JZ int64
,column_CP_SI string
,column_XH_ZK string
,column_UF_XT int64
,column_JJ_WD string
,column_UD_BY int64
,column_BI_ZC date
,column_CQ_XD int64
,column_OF_OX string
,column_FR_OX int64
,column_CZ_IX string
,column_JJ_MT string
,column_TT_PE string
,column_NR_OF int64
,column_CI_UC int64
,column_LS_FL date
,column_IS_YY date
,column_JA_TR string
)
;
