create table db2.table_G (
column_MA_MN int64
,column_CG_GO string
,column_UB_WV string
,column_NV_TS string
,column_TQ_HS string
,column_AT_JF string
,column_MG_HW string
,column_FR_IW string
,column_MO_YO int64
,column_LC_KU string
,column_NB_IM string
,column_NK_JO string
,column_NM_IS string
,column_NI_LZ string
,column_NH_PG string
,column_AC_UQ string
,column_EU_ZC string
,column_SF_QT string
,column_OL_II string
,column_QE_MJ string
,column_IB_QP string
,column_LI_TW string
,column_LX_KY string
,column_JS_NX string
,column_JR_JW string
,column_PF_UV string
,column_JR_AK string
,column_HS_KS string
,column_PR_AC string
,column_CP_QC int64
,column_HV_YO int64
,column_FN_AX date
,column_DV_GB date
,column_EI_LV string
,column_EK_XM string
,column_PW_ZF int64
,column_QE_KW string
,column_KE_VI string
,column_SX_YL string
,column_QL_XA string
,column_OO_TM string
,column_EI_DO int64
,column_MU_YD int64
,column_GT_FC string
,column_FV_SV string
,column_MF_ET string
,column_DO_EB string
,column_MR_OF string
,column_SL_EO string
,column_JV_FX string
,column_NV_JD string
,column_QY_TJ string
,column_GG_FZ string
,column_JT_RD string
,column_YH_KU string
)
;
