create table db2.table_C (
column_PJ_XN int64
,column_CB_BZ string
,column_NF_ZU string
,column_LN_TO string
,column_RF_GB string
,column_GQ_VM string
,column_LM_DY string
,column_CN_AP string
,column_KJ_FJ int64
,column_MK_SZ string
,column_CD_LR string
,column_CR_XM string
,column_CO_ZR string
,column_CH_QP string
,column_CU_QZ string
,column_NA_BG string
,column_PD_YW string
,column_IN_DB string
,column_LJ_OA string
,column_IX_VJ string
,column_TE_RX string
,column_TK_FB string
,column_VH_KO string
,column_TI_PA string
,column_TV_HB string
,column_WV_PD string
,column_TL_RO string
,column_ES_KQ string
,column_UX_JX string
,column_EP_NX int64
,column_UO_LP int64
,column_TF_DE int64
,column_IP_DK date
,column_HD_DN date
,column_IC_YG int64
,column_HK_NR int64
,column_HI_KD string
,column_CY_MZ int64
,column_RW_KC int64
,column_DU_LJ int64
,column_DZ_LY int64
,column_CR_KC int64
,column_EG_MO int64
,column_CR_JD int64
,column_TD_II string
,column_PA_KQ string
,column_NX_LG string
,column_EE_RT string
,column_RB_HU int64
,column_SL_US int64
,column_SB_TR string
,column_CM_RH string
,column_LY_QE string
,column_LC_HH string
,column_MN_LH string
,column_UJ_OE string
,column_TQ_VO string
,column_CB_FI string
,column_YJ_IK string
,column_YS_YT string
,column_QI_DW string
,column_HU_KU string
)
;
