create table db3.table_N (
column_IV_RC int64
,column_UU_BO int64
,column_YE_PS int64
,column_AW_CH int64
,column_BE_KQ int64
,column_CE_CK int64
,column_XF_BW int64
,column_GR_DK int64
,column_PM_OG int64
,column_ZY_AE int64
,column_XD_TO int64
,column_GQ_HB int64
,column_YQ_JP int64
,column_YG_RH int64
,column_WI_HT int64
,column_WY_ME int64
,column_WI_EU int64
,column_WZ_TV int64
,column_WF_NZ int64
,column_FL_RS int64
,column_DE_VM int64
,column_DE_PL int64
,column_BX_GO int64
,column_DH_KI int64
,column_BY_HR int64
,column_DO_IH int64
,column_BT_MT int64
,column_DV_MI int64
,column_BD_GG int64
,column_DX_HF int64
,column_DH_LR int64
,column_XQ_GN int64
,column_VE_RR int64
,column_ZH_CP int64
,column_ZB_TC int64
,column_XM_XE int64
,column_XF_MR int64
,column_XI_BF int64
,column_XL_MR int64
,column_XU_YM int64
,column_EH_HM int64
,column_EQ_CB int64
,column_CL_II int64
,column_EP_QT int64
,column_CO_TN int64
,column_EL_CR int64
,column_CK_UL int64
,column_EF_NC int64
,column_CV_ZY int64
,column_EB_XL int64
,column_EQ_CB int64
,column_YV_IJ int64
,column_WJ_VB int64
,column_FT_QW int64
,column_US_DW int64
,column_RU_JL int64
,column_AD_XS int64
,column_BO_EW int64
,column_VV_LP int64
,column_AZ_GB int64
,column_HX_RG int64
,column_BV_OA int64
,column_WM_NV int64
,column_HS_KI date
,column_UO_HG int64
,column_RP_XZ int64
,column_HH_PU string
)
;
