create table db3.table_M (
column_GT_ZO string
,column_BM_HV int64
,column_WJ_NH string
,column_EG_GA string
,column_OB_GH string
,column_IP_SD string
,column_QO_QX int64
,column_BZ_WD int64
,column_CW_DB int64
,column_XR_RR int64
,column_GU_FF int64
,column_PK_FI int64
,column_ZB_PH int64
,column_XZ_MZ int64
,column_GE_OP int64
,column_YB_YN int64
,column_YT_XJ int64
,column_WU_QE int64
,column_WB_ON int64
,column_WI_EU int64
,column_WY_MQ int64
,column_WT_AR int64
,column_FE_PN int64
,column_DS_VD int64
,column_DX_MM int64
,column_BU_SB int64
,column_DB_RB int64
,column_BR_AY int64
,column_DR_YL int64
,column_BS_BB int64
,column_DO_WU int64
,column_BG_HY int64
,column_DB_UT int64
,column_DR_ID int64
,column_XL_ER int64
,column_VP_NO int64
,column_ZL_XK int64
,column_ZQ_CD int64
,column_XP_CO int64
,column_XC_KP int64
,column_XP_EJ int64
,column_XM_CB int64
,column_XS_AW int64
,column_EB_PA int64
,column_EK_UB int64
,column_CA_YS int64
,column_EK_UL int64
,column_CJ_KC int64
,column_EV_GJ int64
,column_CM_FJ int64
,column_EJ_JY int64
,column_CX_BF int64
,column_EW_MI int64
,column_EZ_PW int64
,column_YX_XD int64
,column_WB_IG int64
,column_FO_AW int64
,column_UW_TV int64
,column_RE_FV int64
,column_AS_SC int64
,column_BI_BP int64
,column_VT_ZS int64
,column_AP_PA int64
,column_HV_RT int64
,column_BS_QB int64
,column_WZ_PS int64
,column_HY_BC date
,column_UD_SV int64
,column_RI_OC int64
,column_HI_CT string
,column_BQ_CD int64
,column_CS_MF int64
,column_XR_TC int64
,column_GA_BI int64
,column_PZ_AK int64
,column_ZS_TS int64
,column_XX_JV int64
,column_GT_XH int64
,column_YE_FP int64
,column_YH_AV int64
,column_WM_QD int64
,column_WF_DF int64
,column_WI_UY int64
,column_WS_GZ int64
,column_WL_WU int64
,column_FB_RE int64
,column_DQ_LW int64
,column_DS_QH int64
,column_BV_GS int64
,column_DJ_ET int64
,column_BK_IG int64
,column_DM_XH int64
,column_BY_FY int64
,column_DE_OX int64
,column_BE_MF int64
,column_DV_OH int64
,column_DG_VS int64
,column_XJ_OQ int64
,column_VR_QK int64
,column_ZO_OE int64
,column_ZF_MD int64
,column_XC_CY int64
,column_XF_FZ int64
,column_XY_PJ int64
,column_XS_LX int64
,column_XK_LK int64
,column_EC_BV int64
,column_EI_EM int64
,column_CS_EM int64
,column_EP_AC int64
,column_CF_JK int64
,column_EF_TI int64
,column_CF_KN int64
,column_EA_ZX int64
,column_CB_TT int64
,column_ED_JA int64
,column_ET_RD int64
,column_YK_SE int64
,column_WT_MJ int64
,column_FQ_LJ int64
,column_UF_LE int64
,column_RT_CA int64
,column_AD_AP int64
,column_BK_GS int64
,column_VL_NP int64
,column_AX_OV int64
,column_HR_WG int64
,column_BC_TU int64
,column_WL_QP int64
,column_HP_EM date
,column_UG_XC int64
,column_RP_QA int64
,column_HL_QQ string
,column_BB_JD int64
,column_CV_OV int64
,column_XT_IN int64
,column_GR_AC int64
,column_PP_XE int64
,column_ZH_ID int64
,column_XY_AA int64
,column_GD_GP int64
,column_YA_HT int64
,column_YR_IK int64
,column_WF_IC int64
,column_WO_QM int64
,column_WB_ML int64
,column_WY_CU int64
,column_WG_GC int64
,column_FR_UC int64
,column_DC_LH int64
,column_DK_UR int64
,column_BZ_UL int64
,column_DA_IS int64
,column_BY_SE int64
,column_DR_UX int64
,column_BM_UP int64
,column_DQ_AH int64
,column_BL_FD int64
,column_DJ_LA int64
,column_DJ_KV int64
,column_XP_DF int64
,column_VL_YX int64
,column_ZD_PB int64
,column_ZJ_PS int64
,column_XS_ZG int64
,column_XF_TK int64
,column_XU_BB int64
,column_XR_ID int64
,column_XX_WZ int64
,column_EU_MG int64
,column_EG_EY int64
,column_CI_ZR int64
,column_EX_ZP int64
,column_CU_IB int64
,column_EM_BG int64
,column_CF_IT int64
,column_ET_JW int64
,column_CW_FE int64
,column_EZ_PR int64
,column_EN_VX int64
,column_YP_JY int64
,column_WN_OG int64
,column_FJ_HU int64
,column_UK_TO int64
,column_RJ_HA int64
,column_AS_IR int64
,column_BW_WD int64
,column_VI_SP int64
,column_AB_CW int64
,column_HE_VI int64
,column_BR_CP int64
,column_WS_FD int64
,column_HE_YT date
,column_UX_DZ int64
,column_RI_MQ int64
,column_HR_PZ string
)
;
