create table db3.table_I (
column_DH_CI int64
,column_FO_AL int64
,column_ZU_AJ int64
,column_XG_WQ int64
,column_FM_RE int64
,column_DL_RX int64
,column_FX_ZU int64
,column_FH_FW int64
,column_DR_MB int64
,column_FQ_JU int64
,column_DY_HO int64
,column_FM_ZT int64
,column_HO_IL int64
,column_HK_IO int64
,column_HR_UY int64
,column_HQ_FI int64
,column_HP_NK int64
,column_HQ_BV int64
,column_JX_GD int64
,column_JT_LW int64
,column_KT_AN int64
,column_JC_PD int64
,column_NB_SY int64
,column_NI_TF int64
,column_MZ_SH int64
,column_PB_AA int64
,column_OA_NS int64
,column_WQ_WN int64
,column_DD_SS int64
,column_DD_HX int64
,column_EU_CE int64
,column_GQ_CK int64
,column_FE_XA int64
,column_DT_QD int64
,column_FL_DZ int64
,column_IC_DA int64
,column_LP_CJ int64
,column_LN_MD int64
,column_LM_LD int64
,column_LY_KI int64
,column_LK_AI int64
,column_LG_KD int64
,column_LK_MP int64
,column_NX_HQ int64
,column_YB_BY int64
,column_BS_AQ int64
,column_BF_UU int64
,column_BW_KU int64
,column_BJ_KF int64
,column_BB_MQ int64
,column_BG_MP int64
,column_NS_DP int64
,column_QP_MG int64
,column_QW_NB int64
,column_QM_LK int64
,column_QP_AF int64
,column_QF_QK int64
,column_QT_XU int64
,column_SC_FM int64
,column_JU_UE string
,column_VN_JH string
,column_GX_VS int64
,column_SC_MN string
,column_UB_OD int64
,column_BM_EG int64
,column_ZM_RI int64
,column_YS_KE int64
,column_FJ_VC int64
,column_HZ_GZ int64
,column_FG_HF int64
,column_HA_BL int64
,column_FG_ZY int64
,column_HA_AR int64
,column_FP_HI int64
,column_HJ_FO int64
,column_FH_VN int64
,column_HC_BQ int64
,column_HD_WP int64
,column_JB_IX int64
,column_CW_JN int64
,column_AG_OF int64
,column_AK_FC int64
,column_AW_WH int64
,column_AF_LG int64
,column_AZ_QE int64
,column_AA_ZH int64
,column_CN_LZ int64
,column_BB_OM int64
,column_BB_VJ int64
,column_BI_HG int64
,column_DS_WD int64
,column_DA_GV int64
,column_DV_CO int64
,column_DA_SW int64
,column_GK_YP int64
,column_CA_JL int64
,column_BP_RI int64
,column_CX_HK int64
,column_CV_YE int64
,column_CS_ZV int64
,column_CQ_GN int64
,column_CH_ZD int64
,column_BT_WB int64
,column_HM_KF int64
,column_WB_EK int64
,column_ML_VA int64
,column_NZ_KV string
,column_HI_KG date
,column_GG_RI int64
,column_DI_AS int64
,column_KH_PB int64
,column_DB_AT int64
,column_EQ_PG int64
,column_NC_XR int64
,column_YO_BA int64
,column_RC_WI string
,column_QN_XJ int64
,column_PE_SH int64
,column_FZ_LE int64
,column_DK_FU int64
,column_EQ_WF int64
,column_ST_VU int64
,column_XT_FE int64
,column_DS_TC int64
,column_FZ_UJ int64
,column_ZX_HQ int64
,column_XI_HZ int64
,column_FM_XP int64
,column_DG_CV int64
,column_FC_OC int64
,column_FE_SN int64
,column_DN_RP int64
,column_FP_UE int64
,column_DJ_GV int64
,column_FE_MO int64
,column_HF_BM int64
,column_HG_PF int64
,column_HY_GT int64
,column_HO_WC int64
,column_HQ_NP int64
,column_HC_SE int64
,column_JL_LD int64
,column_JY_EX int64
,column_KW_MV int64
,column_JU_ZT int64
,column_NF_DV int64
,column_NQ_XR int64
,column_MT_XV int64
,column_PX_LD int64
,column_OC_OM int64
,column_WO_RY int64
,column_DP_HK int64
,column_DM_HO int64
,column_EO_SA int64
,column_GB_WU int64
,column_FK_MO int64
,column_DO_HE int64
,column_FI_UF int64
,column_IY_GI int64
,column_LQ_RZ int64
,column_LB_RN int64
,column_LM_EY int64
,column_LS_DQ int64
,column_LK_ON int64
,column_LT_MJ int64
,column_LR_OS int64
,column_NT_VL int64
,column_YQ_QP int64
,column_BV_CX int64
,column_BM_WB int64
,column_BA_TN int64
,column_BF_LA int64
,column_BQ_PT int64
,column_BD_RP int64
,column_NZ_RH int64
,column_QZ_AN int64
,column_QF_HN int64
,column_QA_JC int64
,column_QO_CT int64
,column_QN_TO int64
,column_QZ_RK int64
,column_SV_DX int64
,column_JY_EM string
,column_VT_VG string
,column_GP_QA int64
,column_SZ_CU string
,column_UJ_FQ int64
,column_BB_PL int64
,column_ZU_RB int64
,column_YJ_VX int64
,column_FU_FI int64
,column_HK_OT int64
,column_FN_BN int64
,column_HM_WM int64
,column_FG_XO int64
,column_HG_KR int64
,column_FO_MH int64
,column_HI_IM int64
,column_FR_GY int64
,column_HR_PG int64
,column_HR_ZJ int64
,column_JE_ZB int64
,column_CE_UL int64
,column_AS_SZ int64
,column_AH_VN int64
,column_AY_YJ int64
,column_AV_WR int64
,column_AD_QM int64
,column_AY_DX int64
,column_CJ_NQ int64
,column_BL_KX int64
,column_BB_HF int64
,column_BD_LY int64
,column_DL_WX int64
,column_DF_UO int64
,column_DG_VH int64
,column_DN_ZY int64
,column_GH_UV int64
,column_CB_HE int64
,column_BP_LA int64
,column_CG_DS int64
,column_CX_KR int64
,column_CR_TJ int64
,column_CR_JS int64
,column_CF_HZ int64
,column_BT_YD int64
,column_HP_NC int64
,column_WJ_XI int64
,column_MU_CF int64
,column_NC_TA string
,column_HA_LE date
,column_GF_FS int64
,column_DX_KO int64
,column_KJ_LL int64
,column_DO_KB int64
,column_EV_EU int64
,column_NR_VN int64
,column_YT_NH int64
,column_RN_TE string
,column_QO_YV int64
,column_PA_ZS int64
,column_FL_AF int64
,column_DW_SM int64
,column_EH_NL int64
,column_SQ_XE int64
,column_XE_PR int64
,column_DN_SU int64
,column_FL_AZ int64
,column_ZZ_UR int64
,column_XT_KC int64
,column_FQ_BC int64
,column_DW_CW int64
,column_FL_VT int64
,column_FH_DP int64
,column_DC_BF int64
,column_FR_TA int64
,column_DF_KV int64
,column_FB_IK int64
,column_HB_IK int64
,column_HK_CA int64
,column_HY_TL int64
,column_HA_QO int64
,column_HD_SJ int64
,column_HC_IX int64
,column_JE_KJ int64
,column_JR_BI int64
,column_KU_KX int64
,column_JZ_NA int64
,column_NA_VB int64
,column_NH_PJ int64
,column_MH_JF int64
,column_PR_NZ int64
,column_OZ_CH int64
,column_WR_JV int64
,column_DY_DL int64
,column_DG_DK int64
,column_EM_GD int64
,column_GQ_TH int64
,column_FP_KD int64
,column_DM_BU int64
,column_FW_SW int64
,column_IG_FC int64
,column_LR_CI int64
,column_LV_CY int64
,column_LM_MQ int64
,column_LH_LM int64
,column_LN_NX int64
,column_LT_QD int64
,column_LB_JJ int64
,column_NM_HR int64
,column_YH_DC int64
,column_BE_WP int64
,column_BL_QR int64
,column_BS_VD int64
,column_BC_DP int64
,column_BI_ZD int64
,column_BH_XT int64
,column_NF_GX int64
,column_QY_OD int64
,column_QR_BW int64
,column_QN_ZU int64
,column_QD_ZO int64
,column_QP_DT int64
,column_QI_HB int64
,column_SZ_FA int64
,column_JL_HB string
,column_VG_BU string
,column_GU_YP int64
,column_SL_PA string
,column_UE_RV int64
,column_BQ_TK int64
,column_ZC_EC int64
,column_YK_YJ int64
,column_FO_IL int64
,column_HN_MU int64
,column_FM_MX int64
,column_HR_MT int64
,column_FV_DE int64
,column_HM_ZY int64
,column_FH_HE int64
,column_HP_WZ int64
,column_FY_OZ int64
,column_HF_AG int64
,column_HZ_WM int64
,column_JG_DZ int64
,column_CY_AE int64
,column_AO_EP int64
,column_AQ_KU int64
,column_AZ_HG int64
,column_AO_WM int64
,column_AM_NE int64
,column_AR_FR int64
,column_CW_PI int64
,column_BC_RH int64
,column_BH_RK int64
,column_BU_AF int64
,column_DP_HN int64
,column_DV_AW int64
,column_DT_QV int64
,column_DJ_FJ int64
,column_GF_ZG int64
,column_CS_MB int64
,column_BD_UX int64
,column_CE_TP int64
,column_CM_IX int64
,column_CK_YA int64
,column_CI_EC int64
,column_CA_PU int64
,column_BE_DG int64
,column_HU_GH int64
,column_WD_NM int64
,column_ML_XZ int64
,column_NJ_TO string
,column_HZ_MC date
,column_GG_GZ int64
,column_DT_CE int64
,column_KW_XN int64
,column_DZ_IF int64
,column_EQ_EX int64
,column_NA_XP int64
,column_YU_PS int64
,column_RC_JH string
,column_QI_YD int64
,column_PB_OD int64
,column_FO_FZ int64
,column_DD_HO int64
,column_EF_BU int64
,column_SY_EV int64
,column_XZ_CF int64
)
;
