create table db3.table_J (
column_DD_MR int64
,column_FP_FE int64
,column_ZI_RU int64
,column_XY_JV int64
,column_FS_AQ int64
,column_DJ_JN int64
,column_FQ_VI int64
,column_FV_MX int64
,column_DD_ME int64
,column_FR_VQ int64
,column_DN_KV int64
,column_FZ_KN int64
,column_HD_IV int64
,column_HG_MO int64
,column_HJ_QU int64
,column_HU_LN int64
,column_HC_PT int64
,column_HB_MZ int64
,column_JJ_II int64
,column_JF_RU int64
,column_KI_SD int64
,column_JN_LE int64
,column_NK_RA int64
,column_NF_UB int64
,column_MM_TV int64
,column_PU_XQ int64
,column_OI_RP int64
,column_WG_DM int64
,column_DX_YO int64
,column_DX_HJ int64
,column_EG_RT int64
,column_GH_IX int64
,column_FZ_EI int64
,column_DB_JO int64
,column_FQ_ON int64
,column_ID_NL int64
,column_LV_MF int64
,column_LH_OA int64
,column_LN_GP int64
,column_LF_FA int64
,column_LP_PS int64
,column_LU_GF int64
,column_LX_XL int64
,column_ND_QB int64
,column_YT_MZ int64
,column_BF_GT int64
,column_BI_UV int64
,column_BU_MU int64
,column_BL_AM int64
,column_BC_TG int64
,column_BC_RR int64
,column_NB_EA int64
,column_QH_QS int64
,column_QZ_DC int64
,column_QE_SD int64
,column_QS_SG int64
,column_QH_AN int64
,column_QP_FI int64
,column_SH_GM int64
,column_JE_QQ string
,column_VO_SU string
,column_GG_GM int64
,column_SM_OO string
,column_UC_EH int64
,column_BX_HZ int64
,column_ZD_DB int64
,column_YS_UI int64
,column_FV_OI int64
,column_HT_LM int64
,column_FJ_ZQ int64
,column_HA_HF int64
,column_FA_MP int64
,column_HW_FD int64
,column_FP_VH int64
,column_HO_IH int64
,column_FX_QZ int64
,column_HA_MY int64
,column_HU_NG int64
,column_JC_IF int64
,column_CC_AA int64
,column_AT_MC int64
,column_AN_EY int64
,column_AD_LW int64
,column_AI_TV int64
,column_AX_SK int64
,column_AP_DO int64
,column_CG_WQ int64
,column_BN_GU int64
,column_BX_GC int64
,column_BB_DG int64
,column_DP_PL int64
,column_DZ_BR int64
,column_DS_CA int64
,column_DO_JS int64
,column_GN_JP int64
,column_CK_CF int64
,column_BM_XM int64
,column_CU_UE int64
,column_CW_GL int64
,column_CG_KS int64
,column_CE_YV int64
,column_CL_JR int64
,column_BV_FS int64
,column_HE_GT int64
,column_WW_OH int64
,column_MP_IE int64
,column_NQ_YJ string
,column_HQ_BG date
,column_GW_OL int64
,column_DG_AI int64
,column_KK_MF int64
,column_DF_ZG int64
,column_EB_UJ int64
,column_NS_OH int64
,column_YF_DB int64
,column_RE_XI string
,column_QU_AS int64
,column_PL_EL int64
,column_FC_YD int64
,column_DE_QA int64
,column_EW_CJ int64
,column_SM_XS int64
,column_XJ_CA int64
)
;
