create table dbo.table_oe (
column_cI_rj_YX string
,column_cM_rj_HP string
,column_de_eo_DX string
,column_cn_lS_XL string
,column_eB_ra_RD string
,column_eB_pa_IS string
,column_cC_rj_XX string
,column_ae_ee_JQ string
,column_nC_il_NV string
,column_ae_ee_LW string
,column_tn_po_PG string
,column_mr_ut_OM string
,column_ee_na_EN string
,column_ef_ok_KO string
,column_de_eo_XR bool
,column_ny_ur_DJ string
,column_po_ol_CR timestamp
,column_po_ol_RX timestamp
,column_pe_ol_QF numeric
,column_ie_ae_RE timestamp
,column_ie_ae_JL timestamp
,column_ie_ae_PE numeric
,column_eS_ln_MW timestamp
,column_eF_ln_GV timestamp
,column_eH_ln_FE numeric
,column_lt_cu_IB timestamp
,column_li_cu_ZS timestamp
,column_lo_cu_UA numeric
,column_ri_ov_PK numeric
,column_nD_ok_VC int64
,column_eD_ln_GT numeric
,column_eF_ln_AP numeric
,column_ie_ae_WO numeric
,column_ie_ae_JV numeric
,column_la_cu_KO numeric
,column_lT_cu_LP numeric
,column_pe_ol_KH numeric
,column_pe_ol_IN numeric
,column_eR_ln_WR numeric
,column_eR_ln_HR numeric
,column_eR_ln_DB numeric
,column_ru_ao_UA numeric
,column_sB_xe_EE numeric
,column_Bd_te_NX numeric
,column_Sa_is_QT timestamp
,column_sr_tt_YJ int64
,column_eo_ra_CJ timestamp
,column_eO_pa_AW timestamp
,column_e_ee_GS bool
,column_Ta_lo_GO bool
,column_cm_eR_EI numeric
,column_j_ea_DM numeric
,column_n_et_FA numeric
,column_eP_sr_SR string
,column_be_il_PT bool
,column_Ep_lo_EY bool
,column_cN_rj_XF string
,column_ct_rj_FC string
,column_ca_rj_JN string
,column_cC_rj_HS string
,column_nC_il_LI string
,column_ae_ee_VN string
,column_lg_lD_NL string
,column_cT_rj_IP string
,column_cV_rj_QL numeric
,column_ef_ok_GZ string
,column_tn_po_ZX string
,column_nP_ur_QX string
,column_rO_rm_AP string
,column_sI_eu_DW string
,column_sn_eu_OU string
,column_eb_ra_BC string
,column_eb_pa_HO string
,column_Po_su_TI int64
,column_se_tt_NI int64
,column_cS_rj_II string
,column_nO_il_LM string
,column_mr_ut_OJ string
,column_ee_na_MI string
,column_cM_rj_EG string
,column_cD_rj_DN string
,column_nO_il_KP string
,column_jc_Pr_HT string
,column_cP_rj_VD string
,column_cS_rj_KW string
,column_ny_ur_XX string
,column_ru_ok_SA string
,column_re_nC_RA string
,column_ee_na_FE string
,column_tv_be_DU string
,column_ln_Pi_VJ string
,column_ln_Pi_XR string
,column_ct_pl_RH string
,column_cA_rj_WW bool
,column_rA_rm_QG string
,column_Ts_lo_MD bool
,column_As_og_DT bool
,column_Ad_og_WK bool
,column_Dl_og_UN bool
,column_rd_uM_PP bool
,column_rd_uM_DM bool
,column_re_uM_WH bool
,column_sd_rp_WK string
,column_sd_rp_UY string
,column_nt_le_VK string
,column_nW_ur_KS string
,column_nW_ur_XV string
,column_nW_ur_HT string
,column_nW_ur_MX string
,column_Ce_lo_NH bool
,column_aS_ip_GF bool
,column_dP_nl_GR bool
,column_iP_ne_UG bool
,column_cl_rt_QR bool
,column_cI_rj_DI string
,column__ae_LO string
)
;
