create table dbo.table_s (
column_eB_ra_UL string
,column_eB_pa_MA string
,column_cN_rj_EN string
,column_mr_ut_KQ string
,column_ee_na_NO string
,column_nO_il_KZ string
,column_nO_il_OY string
,column_sI_eu_HT string
,column_ef_ok_OE string
,column_pe_ol_FV numeric
,column_c_eR_RE numeric
,column_j_eA_KR numeric
,column_n_eT_VL numeric
,column_pc_ol_GC numeric
,column__hs_TZ string
,column_po_ol_MH timestamp
,column_po_ol_NP timestamp
,column_pc_ol_BW timestamp
,column_pc_ol_EI timestamp
,column_ef_ok_QB string
,column_mr_ut_CL string
,column_ee_na_AU string
,column_cI_rj_IN string
,column__ae_TC string
,column_B_S__SM string
,column__B_UC string
,column_dr_BO_HC int64
,column_be_il_VL bool
,column_Fe_ie_XL bool
,column_Fe_ie_KB string
,column_ea_ei_PF string
,column_ak_pn_OK bool
,column_ec_ak_OH string
,column_tt_fe_MQ bool
,column_sN_eu_YX string
,column_eS_ln_UW timestamp
,column_eF_ln_EG timestamp
,column_eH_ln_KP numeric
,column_ie_ae_CW timestamp
,column_ie_ae_JK timestamp
,column_ie_ae_NK numeric
,column_eO_ra_HM timestamp
,column_eB_ra_YS string
,column_eO_pa_OY timestamp
,column_eB_pa_BK string
,column_e_ee_AS bool
,column_d_ok_WR bool
,column_ne_si_UL numeric
,column_e_tf_NX int64
,column_I_hs_SR string
,column_d_ak_RO string
,column_a_ai_LD bool
,column_re_nC_FV string
,column_ee_na_HZ string
,column_ct_pl_HT string
,column_rA_rm_RJ string
,column_cs_rd_LY string
,column_cs_rd_JW string
,column_y_aD_AB int64
,column_tn_ie_RD bool
,column_ee_op_XG bool
,column_nR_il_OY string
,column_nR_il_BK string
,column_in_uc_LN string
,column_in_uc_AU string
,column_Wr_lo_CC bool
,column_Wr_lo_DF bool
,column_rT_um_CD int64
,column_dI_nl_ZI bool
,column_so_tt_NC bool
,column_ri_ov_TI numeric
,column_nD_ok_AQ int64
,column_eD_ln_DR numeric
,column_eF_ln_PM numeric
,column_ie_ae_GI numeric
,column_ie_ae_DQ numeric
,column_pc_ol_ZV numeric
,column_pc_ol_ID numeric
,column_pe_ol_QH numeric
,column_pe_ol_EU numeric
,column_eR_ln_UL numeric
,column_eR_ln_GH numeric
,column_eR_ln_FM numeric
,column_ne_si_KH numeric
,column_ne_si_HR numeric
,column_cl_rt_LL bool
,column__lc_GX int64
,column_cR_rd_VO bool
)
;
