create table dbo.table_so (
column_mr_ut_SL string
,column__ae_DN string
,column_nt_le_HY string
,column_mr_ut_OC string
,column_nM_co_IT string
,column_tu_ae_IW string
,column_ak_ee_LO string
,column_in_ap_QZ string
,column_nT_co_RM string
,column_nT_co_RG string
,column_ta_ae_DH string
,column_mr_ut_VG string
,column_mr_ut_FN string
,column_Sa_ae_RI string
,column_Sa_ae_TP string
,column_es_ui_XF string
,column_es_ui_CE string
,column_es_ui_JI string
,column_es_ui_XQ string
,column_ne_rv_VP string
,column_r1_on_QU string
,column_es_ui_CA string
,column_es_ui_QH string
,column_es_ui_EK string
,column_es_ui_QG string
,column_es_ui_KR string
,column_es_ui_TJ string
,column_es_ui_OW string
,column_es_ui_EH string
,column_es_ui_DG string
,column_ne_rv_AO string
,column_r2_on_AM string
,column_es_ui_BY string
,column_es_ui_HI string
,column_es_ui_SK string
,column_es_ui_TL string
,column_es_ui_AR string
,column_es_ui_ZO string
,column_es_ui_DC string
,column_es_ui_MJ string
,column_es_ui_IV string
,column_ne_rv_FM string
,column_r3_on_OE string
,column_es_ui_IW string
,column_es_ui_NM string
,column_es_ui_KL string
,column_es_ui_OM string
,column_es_ui_LJ string
,column_mr_ut_IQ string
,column_tv_xc_YR string
,column_oe_aP_UO string
,column_n_Rh_EH string
,column_hn_an_DH string
,column_tn_ak_QS string
,column_Po_te_IC string
,column_iy_eu_OE string
,column_ia_eh_IC string
,column_re_ol_IT string
,column_t_eS_BB string
,column_ty_nu_HJ string
,column_nM_co_FA string
,column_ak_ee_YP string
,column_rp_ae_DK string
,column_Rg_ae_CW string
,column_ec_ee_TS bool
,column_Eg_lo_KX bool
,column_ig_tf_SO bool
,column_ei_sr_SV string
,column_ep_aE_SK bool
,column_ep_aE_WI string
,column_in_ap_ZE string
,column_eO_ra_KG timestamp
,column_eB_ra_SH string
,column_eO_pa_WO timestamp
,column_eB_pa_EM string
,column_e_ee_NW bool
,column_eB_ra_OA string
,column_eB_pa_LG string
,column_Rp_ae_OP string
,column_ye_ml_SK string
,column_ye_ml_JS string
,column_le_nu_WU string
,column_le_nu_FX string
,column_ty_nu_UV string
,column_Rg_ae_ZE string
,column_re_AS_VK bool
,column_Rp_lo_OG bool
,column_r1_on_UC string
,column_r2_on_GV string
,column_r3_on_CK string
,column_nO_il_QK string
)
;
