create table dbo.table_qe (
column_mr_ut_IE string
,column_ee_na_LS string
,column_cI_rj_EJ string
,column_cN_rj_FP string
,column_d_ak_JI string
,column_ao_nt_NK string
,column_ek_ep_WE string
,column_n_up_FB int64 
,column_ek_ep_ON string
,column_sN_eu_SB string
,column_sT_eu_XP string
,column_sP_eu_UT string
,column_sP_eu_LQ string
,column_sS_eu_CT string
,column_cN_rd_BV string
,column_iy_un_XU int64
,column_sC_eu_YE string
,column_sS_eu_PO string
,column_Nm_se_TO string
,column_ne_si_AI string
,column_sI_eu_WW string
,column_sT_eu_HX string
,column_sC_eu_SL string
,column_sS_eu_HP string
,column_sS_eu_EM string
,column_IT_EC_GT string
,column_l_ea_HE string
,column__as_UD string
,column_in_ou_ME string
,column_ni_ep_MW string
,column_ec_ee_NM string
,column_te_ae_MZ string
,column_te_ae_QL string
,column_eu_ae_HS timestamp
,column_eO_ra_PR timestamp
,column_eB_ra_RW string
,column_eO_pa_MJ timestamp
,column_eB_pa_TA string
,column_oe_ie_KU string
,column_ne_ep_WC numeric
,column_ui_eo_KA numeric
,column_ae_si_IU numeric
,column_cs_ev_MP numeric
,column_sC_xe_QN numeric
,column_cC_rd_UL numeric
,column_mr_ut_GM string
,column_ee_na_IP string
,column_ao_nt_CF string
,column_cI_rd_DP string
,column_ni_ep_HB string
,column_I_se_ZG string
,column_ne_si_AT string
,column_eB_ra_PC string
,column_eB_pa_QK string
,column_dn_ls_JY timestamp
,column_dy_ls_QM string
,column_dy_ls_CQ string
,column_sA_eu_II int64
,column_so_LR_RV int64
,column_so_LR_UM numeric
,column_sl_LR_UX int64
,column_sl_LR_EF numeric
,column_SA_ai_ED bool
,column__L_II string
,column_so_LR_QG numeric
,column_sl_LR_RL numeric
,column_cl_LE_EV numeric
,column_st_LO_CO int64
,column_2x_LB_MK int64
,column_at_LS_WY string
,column_da_LE_KZ string
,column_at_LS_AX string
,column_di_LE_JY string
,column_mZ_LT_DG string
,column_re_nC_EC string
,column_ee_na_VU string
,column_qe_LR_AF string
,column_qe_LR_KL string
,column_nW_ur_GW string
,column_nW_ur_DJ string
,column_nW_ur_SF string
)
;
