create table dbo.table_na (
column_mr_ut_JK string
,column_x_rf_OZ string
,column_Nm_is_VO string
,column_ea_id_HP string
,column_ae_at_TT string
,column__ae_GQ string
,column_x_uf_KQ string
,column_es_ui_TF string
,column_ns_om_OE string
,column_in_oi_VF string
,column_ru_ok_EX string
,column_e_fi_JU string
,column_si_rf_KE string
,column_eN_aa_OQ string
,column_tn_si_CD string
,column_ea_pu_FQ string
,column_ae_ik_VX string
,column_dy_it_KB timestamp
,column_es_ni_FR timestamp
,column_dr_an_KH string
,column__iy_RN string
,column_es_ui_QA string
,column_r_on_HW string
,column_l_ot_RK string
,column_dr_oe_MM string
,column_iy_oe_LS string
,column_rv_oe_DG string
,column_on_oe_GU string
,column_ot_oe_WE string
,column_Ad_te_WC string
,column_Ct_te_OC string
,column_Po_te_YC string
,column_Cu_te_VG string
,column_Ps_te_PX string
,column_tn_si_SO string
,column_es_ui_DF string
,column_es_ui_IE string
,column_es_ui_FR string
,column_oe_aP_RX string
,column_hn_oe_KD string
,column_hn_oe_WY string
,column_a_oe_ZM string
,column_eP_aa_SQ string
,column_eh_oi_JJ string
,column_Po_te_EN string
,column_Fx_te_EJ string
,column__ae_KY string
,column_rP_rm_GG string
,column_Ad_mi_HB string
,column_Ad_mi_ZK string
,column_Ad_mi_DB string
,column_de_eA_FJ string
,column_eO_ra_DQ timestamp
,column_eB_ra_XQ string
,column_eO_pa_ZH timestamp
,column_eB_pa_YS string
,column_e_ee_LS bool
,column_ee_ae_OJ bool
,column_dr_an_YE string
,column_dr_an_SY string
,column_eB_ra_DV string
,column_eB_pa_NC string
,column_mr_ut_LL string
,column_es_ui_VQ string
,column_es_ui_CP string
,column_rI_on_TX string
,column_rv_oe_AZ string
,column_on_oe_KM string
,column_Po_te_VR string
,column_Cu_te_DR string
,column_cI_ot_XP string
,column_cC_ot_FU string
,column_cC_ot_MV string
,column_cC_ot_ES string
,column_cC_ot_TG string
,column_cC_ot_RE string
,column_cC_ot_EM string
,column_cT_ot_RE string
,column_cT_ot_GU string
,column_cT_ot_PF string
)
;
